// AUTO-GENERATED by scripts/build-sets.mjs — do not edit.
// Set metadata collected from game/data/sets/*.json.

export type SetDefMeta = {
  name: string;
  difficulty: "easy" | "standard" | "hard";
  icon: string;
};

export const setDefsIndex: Record<string, SetDefMeta> = {
  "africa": { name: "Africa", difficulty: "standard", icon: "🦁" },
  "asia": { name: "Asia", difficulty: "standard", icon: "🌏" },
  "capitals": { name: "Capitals of the world", difficulty: "hard", icon: "🏛️" },
  "europe-easy": { name: "Europe · the big names", difficulty: "easy", icon: "🇪🇺" },
  "europe-hard": { name: "Europe · the far corners", difficulty: "hard", icon: "🧭" },
  "europe": { name: "Europe", difficulty: "standard", icon: "🗺️" },
  "germany": { name: "Germany", difficulty: "standard", icon: "🇩🇪" },
  "nordics": { name: "Nordics", difficulty: "easy", icon: "❄️" },
  "north-america": { name: "North America", difficulty: "standard", icon: "🗽" },
  "usa": { name: "USA", difficulty: "standard", icon: "🇺🇸" },
  "world-easy": { name: "World · the big names", difficulty: "easy", icon: "🌍" },
  "world-hard": { name: "World · the ends of the earth", difficulty: "hard", icon: "🏔️" },
  "world": { name: "World", difficulty: "standard", icon: "🌐" },
};
