// Resolve built-in set definitions (game/data/sets/*.json) against the
// compact GeoNames dataset (public/cities5000.json) to generate the City[]
// arrays the game imports. Run after cities5000.json changes or when a
// set definition is edited:
//
//   npm run build:sets

import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// ── Load inputs ─────────────────────────────────────────────────────────

const setsDir = join(root, "game", "data", "sets");

const setFiles = (await readdir(setsDir))
  .filter((f) => f.endsWith(".json"))
  .sort();

const setDefs = [];
for (const file of setFiles) {
  const def = JSON.parse(await readFile(join(setsDir, file), "utf8"));
  def.id = file.slice(0, -5); // filename without .json
  setDefs.push(def);
}

const cities5000 = JSON.parse(
  await readFile(join(root, "public", "cities5000.json"), "utf8"),
);

/**
 * Whether a gazetteer elevation is a real reading. Rows built before
 * build-cities.mjs learned to drop it still carry GeoNames' -9999 "no data"
 * sentinel, and nothing below the Dead Sea is a real settlement.
 */
const usableElevation = (elevation) => elevation !== null && elevation > -500;

// ── Build geonameid → City lookup ──────────────────────────────────────

/** Compact row: [geonameid, countryCode, lat, lon, population, elevation, name, nameDe] */
const byId = new Map();
for (const row of cities5000) {
  byId.set(row[0], row);
}

// ── Resolve each set's cities to City objects ───────────────────────────

const sets = {};
const warnings = [];

for (const def of setDefs) {
  const cities = [];

  for (const geonameId of def.cities) {
    const row = byId.get(geonameId);
    if (!row) {
      warnings.push(`${def.id}: geonameid ${geonameId} not found in cities5000.json — skipped`);
      continue;
    }

    const [, country, latitude, longitude, population, elevation, name, nameDe] = row;
    const city = { id: row[0], name, latitude, longitude, population };
    if (country) city.country = country;
    if (usableElevation(elevation)) city.elevation = elevation;
    if (nameDe) city.nameDe = nameDe;
    cities.push(city);
  }

  // Append override cities (sub-5000 outposts not in cities5000.json).
  if (def.overrides) {
    for (const city of Object.values(def.overrides)) {
      cities.push(city);
    }
  }

  sets[def.id] = cities;
}

if (warnings.length > 0) {
  console.warn(warnings.join("\n"));
}

// ── Generate setDefsIndex.gen.ts (metadata for import in citySets.ts) ───

const indexEntries = setDefs
  .map(
    (def) =>
      `  ${JSON.stringify(def.id)}: ` +
      `{ name: ${JSON.stringify(def.name)}, difficulty: ${JSON.stringify(def.difficulty)}, icon: ${JSON.stringify(def.icon)} },`,
  )
  .join("\n");

const indexFile = `// AUTO-GENERATED by scripts/build-sets.mjs — do not edit.
// Set metadata collected from game/data/sets/*.json.

export type SetDefMeta = {
  name: string;
  difficulty: "easy" | "standard" | "hard";
  icon: string;
};

export const setDefsIndex: Record<string, SetDefMeta> = {
${indexEntries}
};
`;

await writeFile(join(root, "game", "data", "setDefsIndex.gen.ts"), indexFile);

// ── Generate builtSets.gen.ts ──────────────────────────────────────────

const formatCity = (city) => {
  const parts = [`id: ${JSON.stringify(city.id)}`, `name: ${JSON.stringify(city.name)}`];
  if (city.nameDe) parts.push(`nameDe: ${JSON.stringify(city.nameDe)}`);
  if (city.country) parts.push(`country: ${JSON.stringify(city.country)}`);
  parts.push(`latitude: ${city.latitude}`, `longitude: ${city.longitude}`, `population: ${city.population}`);
  if (city.elevation !== undefined) parts.push(`elevation: ${city.elevation}`);
  return `    { ${parts.join(", ")} },`;
};

const blocks = [];
for (const def of setDefs) {
  const cities = sets[def.id];
  const lines = cities.map(formatCity).join("\n");
  blocks.push(`  ${JSON.stringify(def.id)}: [\n${lines}\n  ],`);
}

const genFile = `// AUTO-GENERATED by scripts/build-sets.mjs — do not edit.
// Resolves set definitions in game/data/sets/*.json against public/cities5000.json.
// Run \`npm run build:sets\` after editing a set definition or cities5000.json.

import { City } from "../cities";

export const builtSetCities: Record<string, City[]> = {
${blocks.join("\n")}
};
`;

await writeFile(join(root, "game", "data", "builtSets.gen.ts"), genFile);

const totalCities = Object.values(sets).reduce((sum, c) => sum + c.length, 0);
console.log(
  `Wrote ${Object.keys(sets).length} sets (${totalCities} cities) to game/data/builtSets.gen.ts ` +
    `and setDefsIndex.gen.ts` +
    (warnings.length > 0 ? `, ${warnings.length} warnings` : "") + ".",
);
